process.env.BB_DATA_FILE='/tmp/bb-arena-'+process.pid+'.json';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const progression=require('./progression'),world=require('./world'),grenades=require('./grenades');
function session(){const p=progression.route('profile-create',{name:'Tester',hat:'Cap',skinTone:'#784b35'});return {p,token:p.token,s:progression.route('training-start',{profileToken:p.token,type:'dm',map:0}).training};}
function clock(fn){const old=Date.now;let now=100000;Date.now=()=>now;try{fn(n=>now=n,()=>now)}finally{Date.now=old}}
function openMap(fn){const map=world.maps[0],old={walls:map.walls,propWalls:map.propWalls};map.walls=[];map.propWalls=[];try{fn()}finally{Object.assign(map,old)}}
test('FFA bots choose one another, score their own kills and keep fighting during player respawn',()=>clock((set,get)=>openMap(()=>{const {s,token}=session();Object.assign(s,{x:50,y:35,hp:0,deadUntil:120000});s.targets.forEach((q,i)=>Object.assign(q,{x:5+i*3,y:5,height:0,angle:0,hp:100,nextShot:0,safeUntil:0}));for(let n=0;n<60;n++){set(100000+n*120);progression.route('training-input',{profileToken:token});}assert(s.targets.some(q=>q.shots>0));assert(s.targets.some(q=>q.kills>0));assert(s.feed.some(f=>f.killer!=='Tester'&&f.victim!=='You'));assert.equal(s.kills,0);assert(s.targets.every(q=>q.targetId!=='player'));})))
test('bots roam without a visible opponent and protected players are not targeted',()=>clock((set)=>openMap(()=>{const {s,token}=session();s.safeUntil=200000;Object.assign(s,{x:4,y:5});s.targets.forEach((q,i)=>Object.assign(q,{x:20+i*12,y:30,hp:i===0?100:0,deadUntil:200000}));set(100200);progression.route('training-input',{profileToken:token});assert.equal(s.targets[0].targetId,null);assert(s.targets[0].roamGoal);assert(s.targets[0].path.length);})))
test('all four solo weapons switch while paused, preserve spent magazines and use their own damage/fire rate',()=>clock((set)=>openMap(()=>{const {s,token}=session();for(const key of Object.keys(world.weapons)){progression.route('training-input',{profileToken:token,paused:true,weapon:key});assert.equal(s.weapon,key);assert.equal(s.ammo,world.magazine[key]);}s.ammo=2;progression.route('training-input',{profileToken:token,paused:true,weapon:'rifle'});progression.route('training-input',{profileToken:token,paused:true,weapon:'shotgun'});assert.equal(s.ammo,2);Object.assign(s,{x:2,y:5,angle:0,pitch:0,height:0,nextShot:0,safeUntil:0});s.targets.forEach((q,i)=>Object.assign(q,{x:4+i*5,y:5,hp:i===0?100:0,nextShot:200000,safeUntil:0}));set(100500);progression.route('training-input',{profileToken:token,fire:true,angle:0,pitch:0});assert.equal(s.ammo,1);assert.equal(s.lastDamage,70);assert.equal(s.nextShot,101200);})))
test('grenades consume inventory, bounce without crossing a wall, explode once and respect shields/cover/protection',()=>openMap(()=>{const r={map:0},p={id:'p',x:2,y:5,hp:100,angle:0,grenades:2,height:0,team:0};assert(grenades.throwGrenade(r,p,1000));assert.equal(p.grenades,1);assert(!grenades.throwGrenade(r,p,1100));const g=r.projectiles[0];Object.assign(g,{x:5,y:5,height:1,explodeAt:1000});const exposed={id:'e',x:6,y:5,height:0,hp:100,shield:50},safe={id:'s',x:5,y:6,hp:100,safeUntil:2000};let hits=0;grenades.advance(r,[p,exposed,safe],1000,.1,()=>hits++);assert(exposed.shield<50);assert.equal(safe.hp,100);assert.equal(r.projectiles.length,0);const first=hits;grenades.advance(r,[p,exposed,safe],1100,.1,()=>hits++);assert.equal(hits,first);world.maps[0].walls=[[5.5,4,1,2]];world.maps[0].wallHeights=[3];r.projectiles=[{...g,done:false,x:5,height:1,explodeAt:2000}];exposed.hp=100;exposed.shield=50;grenades.advance(r,[p,exposed],2000,.1,()=>{});assert.equal(exposed.hp,100);assert.equal(exposed.shield,50);r.projectiles=[{...g,done:false,x:5,height:1,vx:10,vy:0,vz:0,explodeAt:4000}];grenades.advance(r,[p],3000,.12,()=>{});assert(r.projectiles[0].x<5.5);}));
test('cosmetics persist and invalid values cannot replace saved choices',()=>{const {token}=session();let p=progression.route('profile-get',{profileToken:token}).profile;assert.equal(p.hat,'Cap');assert.equal(p.skinTone,'#784b35');p=progression.route('profile-edit',{profileToken:token,hat:'Beanie',skinTone:'#4c3027'}).profile;assert.equal(p.hat,'Beanie');p=progression.route('profile-edit',{profileToken:token,hat:'invalid',skinTone:'invalid'}).profile;assert.equal(p.hat,'Beanie');assert.equal(p.skinTone,'#4c3027');});
test('tracer copies the authoritative ray and excludes only an identified shooter',()=>openMap(()=>{const p={id:'p',x:2,y:5,angle:0,hp:100},q={id:'q',x:5,y:5,hp:100};const shot=world.traceShot({map:0},p,[p,q],world.weapons.rifle);assert.equal(shot.target,q);const r={};world.addTracer(r,shot);assert.equal(r.tracers[0].targetId,'q');assert.equal(r.tracers[0].shooterId,'p');assert.deepEqual(r.tracers[0].to,shot.to);shot.to[0]=999;assert.notEqual(r.tracers[0].to[0],999);}));
test('home has separate tutorial layout selector and every referenced UI element exists once',()=>{const html=fs.readFileSync('public/index.html','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const file of ['public/interface.js','public/progression-ui.js','public/profile-guide.js'])for(const m of fs.readFileSync(file,'utf8').matchAll(/\$\('([^']+)'\)/g))assert(ids.includes(m[1]),file+' '+m[1]);assert(html.includes('id="tutorialMap"'));assert(html.includes('data-view="tutorials"'));});
test('terrain beginner target respawns stay inside the playable range',()=>clock((set)=>{const {token}=session(),s=progression.route('training-start',{profileToken:token,type:'aim',map:2}).training;s.targets[0].hp=0;s.targets[0].deadUntil=0;set(100120);progression.route('training-input',{profileToken:token});assert.equal(s.targets[0].hp,100);assert(!world.blocked(s,s.targets[0].x,s.targets[0].y));assert(s.targets[0].y>30);}));
test('online FFA permits same-color opponents to fight, gives all guns and finishes with individual scoring',async()=>{const {server,rooms,shoot,tick}=require('./server');await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;async function api(action,b){const response=await fetch(base+'/api/'+action,{method:'POST',body:JSON.stringify(b)});const result=await response.json();assert.equal(response.status,200,result.error);return result;}try{const a=await api('create',{mode:'dm',name:'Alpha',map:0}),b=await api('join',{code:a.state.code,name:'Bravo'});await api('start',{id:a.id});const r=rooms.get(a.state.code),[p,q]=r.players;assert.equal(p.owned.length,4);assert.equal(r.zones.length,0);const walls=world.maps[0].walls,props=world.maps[0].propWalls;world.maps[0].walls=[];world.maps[0].propWalls=[];try{Object.assign(p,{x:2,y:5,angle:0,pitch:0,height:0,team:0,safeUntil:0});Object.assign(q,{x:4,y:5,height:0,team:0,safeUntil:0,shield:0,hp:30});shoot(r,p);assert.equal(q.hp,0);assert.equal(p.kills,1);assert.deepEqual(r.score,[0,0]);p.kills=20;tick();assert.equal(r.phase,'results');assert.equal(r.winnerName,'Alpha');assert.equal(p.rewardCoins,125);}finally{world.maps[0].walls=walls;world.maps[0].propWalls=props;}}finally{rooms.clear();await new Promise(resolve=>server.close(resolve));}});
test('armory HUD button resets all opposing anchors and has a bounded height',()=>{const css=fs.readFileSync('public/style.css','utf8');const rules=[...css.matchAll(/#hud #ingameShop\{([^}]+)\}/g)].map(m=>m[1]);assert(rules.length>=3);for(const rule of rules){assert(rule.startsWith('inset:auto;'));const properties=Object.fromEntries(rule.split(';').filter(Boolean).map(p=>p.split(':')));assert(!(properties.top&&properties.bottom));assert(!(properties.left&&properties.right));}assert(rules[0].includes('height:36px'));assert(rules[0].includes('width:max-content'));});
test('four distinct gun previews are bundled and served as SVG images',async()=>{const {server}=require('./server');await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const previews=[];try{for(const key of Object.keys(world.weapons)){const response=await fetch('http://127.0.0.1:'+server.address().port+'/weapon-'+key+'.svg');assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/svg+xml');const text=await response.text();assert(text.includes('<svg'));assert(text.includes(key+' weapon preview'));previews.push(text);}assert.equal(new Set(previews).size,4);}finally{await new Promise(resolve=>server.close(resolve));}});
