const grenades=require('./grenades');
const terrain=require('./public/terrain');
const recoil=require('./public/recoil');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dataPath=process.env.BB_DATA_FILE||path.join(__dirname,'data','progression.json');
let db={profiles:{},guilds:{}};if(fs.existsSync(dataPath))db=JSON.parse(fs.readFileSync(dataPath,'utf8'));
const movement=require('./public/movement');
const drills=new Map(),regions=['North America','Europe','South Asia','Asia Pacific'];
const tier=rating=>rating<1100?'Rookie':rating<1300?'Bronze':rating<1600?'Silver':'Gold';
function save(){fs.mkdirSync(path.dirname(dataPath),{recursive:true});const tmp=dataPath+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,dataPath)}
function profile(token){return Object.values(db.profiles).find(p=>p.token===token)}
function publicProfile(p){normalize(p);const {token,...safe}=p;const regionPlayers=Object.values(db.profiles).filter(x=>x.region===p.region).sort((a,b)=>b.rating-a.rating||b.wins-a.wins);return {...safe,backstory:p.backstory||'',level:1+Math.floor((p.xp||0)/100),xpToNext:100-(p.xp||0)%100,regionRank:regionPlayers.findIndex(x=>x.id===p.id)+1,regionPopulation:regionPlayers.length,tier:tier(p.rating),guild:p.guildId?db.guilds[p.guildId]:null}}
function directory(region){return Object.values(db.guilds).filter(g=>!region||g.region===region).sort((a,b)=>b.rating-a.rating).map(g=>({...g,tier:tier(g.rating),members:g.members.map(id=>{const p=db.profiles[id];return {id:p.id,name:p.name,rating:p.rating,color:p.color,emblem:p.emblem}})}))}
function payload(p){return {profile:publicProfile(p),guilds:directory(p.region)}}
function activeProfile(token){const p=profile(token);if(!p)throw Error('Create or select your operator profile first.');return p}
const {combatUpdate,damage,traceShot,addTracer,jumpPhysics,magazine,maps,props,weapons,blocked,visible,move,captureSeconds}=require('./world');
const trainingSpawns=[{x:4,y:5},{x:9,y:4},{x:14,y:10},{x:19,y:16},{x:25,y:15},{x:18,y:4},{x:10,y:15}];
const tutorials=['aim','assault'];
// Preserve completion earned in old versions; the old capture + survival pair becomes one tutorial.
function normalize(p){p.completed??=[];if(p.completed.includes('capture')&&p.completed.includes('survive')&&!p.completed.includes('assault'))p.completed.push('assault');return p}
function tutorialCount(p){normalize(p);return tutorials.filter(t=>p.completed.includes(t)).length}
function resetSolo(s,now){recoil.reset(s);s.x=s.base?.x||2;s.y=s.base?.y||10;s.hp=100;s.grenades=2;s.grenadeHeld=false;s.magazines={};s.shield=50;s.ammo=magazine[s.weapon];s.reloadUntil=0;s.angle=0;s.pitch=0;s.safeUntil=now+2500;s.deadUntil=0;movement.reset(s);s.height=terrain.surface(s.mapInfo,s.x,s.y)}
function beginTraining(p,type,mapIndex=0){if(type==='capture'||type==='survive')type='assault';if(!['aim','assault','dm'].includes(type))throw Error('Unknown game mode.');const now=Date.now(),map=Math.max(0,Math.min(maps.length-1,Number(mapIndex)||0));const s={type,map,mapInfo:{...maps[map],props:maps[map].props||props},weapon:'rifle',grenades:2,x:2,y:10,angle:0,pitch:0,height:0,verticalVelocity:0,hp:100,shield:50,ammo:30,reloadUntil:0,hits:0,kills:0,deaths:0,progress:0,stage:0,remaining:type==='aim'?90:type==='dm'?180:240,targets:trainingSpawns.slice(type==='aim'?0:2,type==='aim'?4:5).map((t,i)=>({...t,id:'bot-'+i,name:type==='aim'?'Range target':'Harbor defender '+(i+1),team:1,hp:100,shield:0,angle:Math.PI,pitch:0,nextShot:now+2500,deadUntil:0,kills:0})),zones:[],flag:{x:25,y:10,homeX:25,homeY:10,carried:false,dropUntil:0},base:{x:2,y:10},started:now,last:now,nextShot:0,safeUntil:now+2500,done:false,failed:false,reward:0,feed:[],notice:type==='assault'?'Steal the blue flag. Return it to your orange base. Three deliveries win.':type==='dm'?'Three-minute deathmatch. Eliminations earn coins; deaths respawn.':'Eliminate 10 targets. Aim for the head.'};if(maps[map].terrain){const home=maps[map].spawns[0],flag=maps[map].flagHome;Object.assign(s,{x:home.x,y:home.y,base:{...home},remaining:type==='assault'?360:s.remaining});Object.assign(s.flag,{x:flag.x,y:flag.y,homeX:flag.x,homeY:flag.y});s.targets.forEach((q,i)=>{const spot=type==='aim'?[{x:14,y:43},{x:18,y:38},{x:24,y:40},{x:16,y:34}][i]:maps[map].botSpawns[i];Object.assign(q,spot,{height:terrain.surface(maps[map],spot.x,spot.y)});});}s.weapons=weapons;if(type==='dm')s.targets.forEach((q,i)=>{Object.assign(q,maps[map].botSpawns[i],{name:['Rook','Viper','Echo'][i],color:['#51cfe1','#a898ff','#a6d35c'][i],hat:['Helmet','Cap','Beanie'][i],deaths:0});q.height=terrain.surface(s.mapInfo,q.x,q.y)});recoil.reset(s);movement.reset(s);s.height=terrain.surface(s.mapInfo,s.x,s.y);drills.set(p.id,s);return s}
function pathTo(s,q,goal){const sx=Math.max(0,Math.min(s.mapInfo.width-1,Math.floor(q.x))),sy=Math.max(0,Math.min(s.mapInfo.depth-1,Math.floor(q.y))),tx=Math.max(0,Math.min(s.mapInfo.width-1,Math.floor(goal.x))),ty=Math.max(0,Math.min(s.mapInfo.depth-1,Math.floor(goal.y)));const key=(x,y)=>y*s.mapInfo.width+x,queue=[[sx,sy]],prev=new Map([[key(sx,sy),null]]);let found=null;
for(let at=0;at<queue.length;at++){const [x,y]=queue[at];if(x===tx&&y===ty){found=[x,y];break}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx<0||ny<0||nx>=s.mapInfo.width||ny>=s.mapInfo.depth||prev.has(k)||blocked(s,nx+.5,ny+.5))continue;prev.set(k,[x,y]);queue.push([nx,ny])}}
if(!found)return [];const path=[];while(found&&key(...found)!==key(sx,sy)){path.push({x:found[0]+.5,y:found[1]+.5});found=prev.get(key(...found))}return path.reverse()}
function dmBots(s,now,dt){
 const competitors=[s,...s.targets];
 for(const q of s.targets){
  if(q.hp<=0){if(now>=q.deadUntil){const spots=maps[s.map].botSpawns,alive=competitors.filter(x=>x!==q&&x.hp>0);const spot=[...spots].sort((a,b)=>Math.min(...alive.map(x=>Math.hypot(b.x-x.x,b.y-x.y)),100)-Math.min(...alive.map(x=>Math.hypot(a.x-x.x,a.y-x.y)),100))[0];movement.reset(q);Object.assign(q,spot,{hp:100,height:terrain.surface(s.mapInfo,spot.x,spot.y),safeUntil:now+1500,nextShot:now+1500,path:[],targetId:null});}continue;}
  const candidates=competitors.filter(x=>x!==q&&x.hp>0&&now>=(x.safeUntil||0)&&Math.hypot(x.x-q.x,x.y-q.y)<22&&visible(s,q,x));
  candidates.sort((a,b)=>Math.hypot(a.x-q.x,a.y-q.y)-Math.hypot(b.x-q.x,b.y-q.y));
  const target=candidates.find(x=>(x.id||'player')===q.targetId)||candidates[0];
  q.targetId=target?(target.id||'player'):null;
  if(!target&&(!q.roamGoal||Math.hypot(q.x-q.roamGoal.x,q.y-q.roamGoal.y)<1||now>q.roamUntil)){const spots=maps[s.map].botSpawns;q.roamIndex=((q.roamIndex??Number(q.id.slice(-1)))+1)%spots.length;q.roamGoal=spots[q.roamIndex];q.roamUntil=now+12000;q.routeAt=0;}
  const goal=target||q.roamGoal,distance=target?Math.hypot(target.x-q.x,target.y-q.y):Infinity;
  if(!target||distance>9){if(now>=(q.routeAt||0)){q.path=pathTo(s,q,goal);q.routeAt=now+900;}while(q.path?.length&&Math.hypot(q.x-q.path[0].x,q.y-q.path[0].y)<.4)q.path.shift();const next=q.path?.[0];if(next){q.angle=Math.atan2(next.y-q.y,next.x-q.x);movement.advance(s.mapInfo,q,{forward:.55},dt);}}
  if(!target)continue;
  q.angle=Math.atan2(target.y-q.y,target.x-q.x);q.pitch=Math.atan2((target.height||0)+1.25-(q.height||0)-movement.eye(q),Math.max(.01,distance))+Math.sin(now*.003+Number(q.id.slice(-1)))*.012;
  if(now<q.nextShot||now<(q.safeUntil||0))continue;
  q.nextShot=now+320;q.flashUntil=now+90;q.shots=(q.shots||0)+1;
  const shot=traceShot(s,q,competitors.filter(x=>x!==q&&now>=(x.safeUntil||0)),{damage:16,headDamage:40,range:22});addTracer(s,shot);
  if(!shot.target)continue;const victim=shot.target;damage(victim,shot.damage,now);victim.damageUntil=now+350;victim.damageAngle=Math.atan2(q.y-victim.y,q.x-victim.x);
  if(victim.hp<=0){q.kills++;victim.deaths=(victim.deaths||0)+1;victim.killedAt=now;victim.deadUntil=now+3000;s.feed.unshift({killer:q.name,victim:victim===s?'You':victim.name,weapon:'Patrol rifle',team:1,at:now});s.feed=s.feed.slice(0,6);}
 }
}
function bots(s,now,dt){if(s.type==='dm')return dmBots(s,now,dt);for(const q of s.targets){if(q.hp<=0){if(now>=q.deadUntil){const i=Number(q.id.slice(-1)),spot=s.type==='aim'?(s.mapInfo.terrain?[{x:14,y:43},{x:18,y:38},{x:24,y:40},{x:16,y:34}]:trainingSpawns)[(s.hits+i)%(s.mapInfo.terrain?4:trainingSpawns.length)]:(s.type==='dm'||s.mapInfo.terrain?maps[s.map].botSpawns:[{x:25,y:5},{x:24,y:10},{x:25,y:15}])[i%3];Object.assign(q,spot,{hp:100,height:terrain.surface(s.mapInfo,spot.x,spot.y),nextShot:now+1800,damageUntil:0,path:[]});if(s.mapInfo.terrain){movement.reset(q);q.height=terrain.surface(s.mapInfo,q.x,q.y)}}continue}if(s.type==='aim')continue;
const distance=Math.hypot(s.x-q.x,s.y-q.y),canSee=s.hp>0&&visible(s,q,s);const goal=s.type==='dm'||canSee?s:{x:s.flag?.carried?s.x:s.flag.homeX-2,y:s.flag?.carried?s.y:s.flag.homeY};
if(distance>3||!canSee){if(!q.routeAt||now>=q.routeAt){q.path=pathTo(s,q,goal);q.routeAt=now+700}while(q.path?.length&&Math.hypot(q.x-q.path[0].x,q.y-q.path[0].y)<.25)q.path.shift();const next=canSee?goal:q.path?.[0];if(next){q.angle=Math.atan2(next.y-q.y,next.x-q.x);s.mapInfo.terrain?movement.advance(s.mapInfo,q,{forward:.6},dt):move(s,q,1,0,dt,2.3)}}
if(canSee&&distance<22){q.angle=Math.atan2(s.y-q.y,s.x-q.x);q.pitch=Math.atan2((s.height||0)+movement.eye(s)-(q.height||0)-movement.eye(q),Math.max(.01,distance))+Math.sin(now*.003+Number(q.id.slice(-1)))*.045;if(now>=q.nextShot&&now>=s.safeUntil){q.nextShot=now+900;q.flashUntil=now+90;q.shots=(q.shots||0)+1;const shot=traceShot(s,q,[s],{damage:9,headDamage:14,range:22});addTracer(s,shot);if(shot.target){damage(s,shot.damage,now);s.damageUntil=now+350;s.damageAngle=Math.atan2(q.y-s.y,q.x-s.x);s.notice='Incoming fire from '+q.name;if(s.hp<=0){q.kills++;s.deaths++;s.deadUntil=now+2500;s.notice='Eliminated by '+q.name+'. Respawning in 3 seconds.';if(s.flag.carried){s.flag.carried=false;s.flag.x=s.x;s.flag.y=s.y;s.flag.dropUntil=now+10000}s.feed.unshift({killer:q.name,victim:'You',weapon:'Patrol rifle',team:1,at:now})}}}}}}
function finishSolo(p,s,now){if(s.rewarded)return;s.rewarded=true;if(s.type==='dm'){s.reward=25+Math.min(200,s.kills*5);p.coins+=s.reward;p.xp+=(20+s.kills*3);p.matches=(p.matches||0)+1;}else{normalize(p);const first=!p.completed.includes(s.type),lastReward=p.challengeRewards?.[s.type]||0;s.reward=first?120:now-lastReward>=60000?20:0;p.coins+=s.reward;p.xp+=first?100:10;p.challengeRewards??={};p.challengeRewards[s.type]=now;if(first)p.completed.push(s.type)}save()}
function advanceSoloGrenades(p,s,now,dt){grenades.advance(s,[s,...s.targets],now,dt,(owner,victim,amount,killed)=>{if(owner===s&&victim!==s){s.lastDamage=amount;s.lastHitZone='blast';s.hitSerial=(s.hitSerial||0)+1;s.hitUntil=now+200;}if(killed){victim.killedAt=now;victim.deadUntil=now+3000;victim.deaths=(victim.deaths||0)+1;if(victim!==owner){owner.kills++;if(owner===s){s.hits++;s.killUntil=now+900;}}s.feed.unshift({killer:owner===s?p.name:owner.name,victim:victim===s?'You':victim.name,weapon:'Frag grenade',team:owner===s?0:1,at:now});s.feed=s.feed.slice(0,6);}});}
function updateTraining(p,b){const s=drills.get(p.id);if(!s)throw Error('Start a game first.');if(s.done||s.failed)return s;const now=Date.now(),dt=Math.max(0,Math.min(.12,(now-s.last)/1000));s.last=now;
// Esc/settings pause solo sessions, including bots and the clock; the first resumed update never catches up hidden time.
if(b.weapon&&Object.hasOwn(weapons,b.weapon)&&b.weapon!==s.weapon&&s.hp>0){s.magazines??={};s.magazines[s.weapon]=s.ammo;s.weapon=b.weapon;s.ammo=s.magazines[b.weapon]??magazine[b.weapon];s.reloadUntil=0;s.nextShot=now+250;recoil.reset(s);}if(b.paused)return s;s.remaining=Math.max(0,s.remaining-dt);advanceSoloGrenades(p,s,now,dt);if(s.hp<=0){if(now>=s.deadUntil)resetSolo(s,now);else{if(s.type==='dm')bots(s,now,dt);if(s.remaining<=0){s.done=s.type==='dm';s.failed=!s.done;s.failureReason='Time expired before all three flag deliveries.';if(s.done)finishSolo(p,s,now)}return s}}
if(Number.isFinite(b.angle))s.angle=b.angle;if(Number.isFinite(b.pitch))s.pitch=Math.max(-1.45,Math.min(1.45,b.pitch));combatUpdate(s,s.weapon,now,dt,b.reload);movement.advance(s.mapInfo,s,{forward:b.forward,strafe:b.strafe,jump:b.jump,crouch:b.crouch,aim:b.aim},dt);
if(b.fire&&now>=s.nextShot&&!s.reloadUntil&&s.ammo>0){s.ammo--;s.nextShot=now+weapons[s.weapon].interval;s.shots=(s.shots||0)+1;s.flashUntil=now+90;const shot=traceShot(s,recoil.fire(s,s.weapon,now,!!b.aim),s.targets.filter(q=>now>=(q.safeUntil||0)),weapons[s.weapon]),target=shot.target;addTracer(s,shot);if(target){target.hp=Math.max(0,target.hp-shot.damage);target.damageUntil=now+220;target.lastDamage=shot.damage;s.lastDamage=shot.damage;s.lastHitZone=shot.zone;s.hitSerial=(s.hitSerial||0)+1;s.hitUntil=now+200;if(target.hp<=0){target.killedAt=now;target.deadUntil=now+(s.type==='aim'?1200:3000);target.deaths=(target.deaths||0)+1;s.hits++;s.kills++;s.killUntil=now+900;s.feed.unshift({killer:p.name,victim:target.name,weapon:weapons[s.weapon].name,team:0,headshot:shot.zone==='head',at:now});s.feed=s.feed.slice(0,6)}}}
if(b.grenade&&!s.grenadeHeld)grenades.throwGrenade(s,s,now);s.grenadeHeld=!!b.grenade;

bots(s,now,dt);
if(s.type==='assault'&&s.hp>0){const flag=s.flag;if(flag.dropUntil&&now>=flag.dropUntil){flag.x=flag.homeX;flag.y=flag.homeY;flag.dropUntil=0}if(!flag.carried&&Math.hypot(s.x-flag.x,s.y-flag.y)<1.15&&Math.abs(s.height-terrain.surface(s.mapInfo,flag.x,flag.y))<1.5){flag.carried=true;flag.dropUntil=0;s.notice='FLAG TAKEN / Return to the orange base'}if(flag.carried&&Math.hypot(s.x-s.base.x,s.y-s.base.y)<1.5&&Math.abs(s.height-terrain.surface(s.mapInfo,s.base.x,s.base.y))<1.5){s.stage++;flag.carried=false;flag.x=flag.homeX;flag.y=flag.homeY;s.notice='Flag delivered / '+s.stage+' of 3';s.safeUntil=now+1500}}
if((s.type==='aim'&&s.hits>=10)||(s.type==='assault'&&s.stage>=3)||(s.type==='dm'&&s.remaining<=0)){s.done=true;finishSolo(p,s,now)}else if(s.remaining<=0){s.failed=true;s.failureReason=s.type==='aim'?'Time expired: '+s.hits+' of 10 targets eliminated.':'Time expired: '+s.stage+' of 3 flags delivered.'}return s}
function route(action,b){if(action==='profile-create'){const p={id:crypto.randomUUID(),token:crypto.randomBytes(24).toString('hex'),name:String(b.name||'Operator').trim().slice(0,18)||'Operator',region:regions.includes(b.region)?b.region:regions[0],hat:['Helmet','Cap','Beanie','None'].includes(b.hat)?b.hat:'Helmet',skinTone:['#f3d4b5','#d8ab83','#ad7751','#784b35','#4c3027'].includes(b.skinTone)?b.skinTone:'#d8ab83',color:['#ff814a','#51cfe1','#a898ff','#a6d35c'].includes(b.color)?b.color:'#ff814a',emblem:['Vanguard','Sentinel','Scout'].includes(b.emblem)?b.emblem:'Vanguard',backstory:String(b.backstory||'').slice(0,1200),coins:100,xp:0,rating:1000,completed:[],guildId:null,wins:0};db.profiles[p.id]=p;save();return {token:p.token,...payload(p)}}
if(!action.startsWith('profile-')&&!action.startsWith('guild-')&&!action.startsWith('training-'))return null;const p=activeProfile(b.profileToken);
if(action==='profile-get')return payload(p);
if(action==='profile-edit'){if(['Helmet','Cap','Beanie','None'].includes(b.hat))p.hat=b.hat;if(['#f3d4b5','#d8ab83','#ad7751','#784b35','#4c3027'].includes(b.skinTone))p.skinTone=b.skinTone;if(typeof b.backstory==='string')p.backstory=b.backstory.slice(0,1200);p.name=String(b.name||p.name).trim().slice(0,18);if(!p.guildId&&regions.includes(b.region))p.region=b.region;if(['#ff814a','#51cfe1','#a898ff','#a6d35c'].includes(b.color))p.color=b.color;if(['Vanguard','Sentinel','Scout'].includes(b.emblem))p.emblem=b.emblem;save();return payload(p)}
if(action==='guild-directory')return {guilds:directory(p.region)};
if(action==='guild-create'){if(p.guildId)throw Error('Leave your current guild first.');if(p.coins<250)throw Error('Earn 250 coins in matches or tutorials to found a guild.');if(p.coins<250)throw Error('Guild creation costs 250 personal coins.');const name=String(b.name||'').trim().slice(0,24);if(name.length<3)throw Error('Use at least three characters for your guild name.');if(Object.values(db.guilds).some(g=>g.name.toLowerCase()===name.toLowerCase()))throw Error('That guild name is taken.');const g={id:crypto.randomUUID(),name,tag:String(b.tag||name.slice(0,3)).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4)||'NEW',region:p.region,leader:p.id,members:[p.id],rating:1000,coins:0,energy:100,wins:0};db.guilds[g.id]=g;p.guildId=g.id;p.coins-=250;save();return payload(p)}
if(action==='guild-join'){if(p.guildId)throw Error('Leave your current guild first.');const g=db.guilds[b.guildId];if(!g||g.region!==p.region)throw Error('Choose a guild in your region.');if(g.members.length>=8)throw Error('Guild is full (8 members).');g.members.push(p.id);p.guildId=g.id;save();return payload(p)}
if(action==='guild-leave'){const g=db.guilds[p.guildId];if(g){g.members=g.members.filter(id=>id!==p.id);if(!g.members.length)delete db.guilds[g.id];else if(g.leader===p.id)g.leader=g.members[0]}p.guildId=null;save();return payload(p)}
if(action==='guild-donate'){const g=db.guilds[p.guildId];if(!g)throw Error('Join a guild first.');if(p.coins<50)throw Error('Donation costs 50 personal coins.');p.coins-=50;g.coins+=50;save();return payload(p)}
if(action==='training-start')return {training:beginTraining(p,b.type,b.map)};
if(action==='training-input')return {training:updateTraining(p,b),...(drills.get(p.id)?.done?payload(p):{})};
throw Error('Unknown progression action.')}
function rewardWar(r,winner){if(!r.guildIds?.every(Boolean))return;for(const [t,gid]of r.guildIds.entries()){const g=db.guilds[gid];if(!g)continue;g.coins+=t===winner?30:10;r.coins[t]=g.coins;g.energy=r.energy[t];g.rating=Math.max(800,g.rating+(t===winner?25:-15));if(t===winner)g.wins++;for(const player of r.players.filter(p=>p.team===t)){const p=db.profiles[player.profileId];if(p){p.rating=Math.max(800,p.rating+(t===winner?20:-10));p.coins+=t===winner?40:15;p.xp=(p.xp||0)+(t===winner?50:25);if(t===winner)p.wins++}}}save()}
module.exports={route,profile,publicProfile,db,save,tier,rewardWar,drills,tutorialCount};
