process.env.BB_DATA_FILE=require('node:path').join(require('node:os').tmpdir(),'bb-test-'+require('node:crypto').randomUUID()+'.json');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {server,rooms,tick,roundEnd,shoot}=require('./server');
test('multiplayer war: combat, capture, contest, overtime, rewards, purchase, rematch, room cap',async()=>{
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
async function api(action,data={}){const r=await fetch(base+'/api/'+action,{method:'POST',body:JSON.stringify(data)});return {status:r.status,...await r.json()}}
try{const a=await api('create',{name:'Alpha'}),b=await api('join',{name:'Bravo',code:a.state.code});assert.equal(b.state.players.length,2);assert.equal((await api('start',{id:b.id})).status,400);await api('start',{id:a.id});const r=rooms.get(a.state.code);assert.deepEqual(r.energy,[80,80]);const input=await api('input',{id:a.id,forward:1,pitch:.3,angle:0});assert.equal(input.status,200);assert.equal(input.state.players[0].pitch,.3);r.players[0].pitch=0;r.players[0].input={};assert.equal((await api('join',{code:r.code})).status,400);const [p,q]=r.players;p.x=2;p.y=10;p.angle=0;q.x=4;q.y=10;q.safeUntil=0;for(let i=0;i<5;i++){p.nextShot=0;shoot(r,p)}assert.equal(q.hp,0);assert.equal(p.kills,1);q.deadUntil=0;tick();assert.equal(q.hp,100);p.x=9;p.y=4;q.x=26;q.y=10;for(let i=0;i<505;i++){p.lastSeen=q.lastSeen=Date.now();tick();if(i===100)assert.equal(r.zones[0].owner,-1)}assert.equal(r.zones[0].owner,0);assert.equal(p.captures,1);q.x=9;q.y=4;r.zones[0].owner=-1;r.zones[0].progress=0;for(let i=0;i<120;i++){p.lastSeen=q.lastSeen=Date.now();tick()}assert.equal(r.zones[0].owner,-1);r.remaining=.01;r.score=[10,10];tick();assert.equal(r.overtime,true);q.x=26;for(let i=0;i<510;i++){p.x=14;p.y=10;p.lastSeen=q.lastSeen=Date.now();tick()}assert.equal(r.phase,'intermission');r.nextAt=0;tick();assert.equal(r.round,2);assert.equal(r.map,1);roundEnd(r,0);assert.equal(r.phase,'results');assert.deepEqual(r.coins,[30,10]);await api('buy',{id:a.id});assert.deepEqual(r.energy,[100,80]);assert.deepEqual(r.coins,[10,10]);assert.equal((await api('buy',{id:b.id})).status,400);await api('start',{id:a.id});assert.deepEqual(r.energy,[80,60]);assert.deepEqual(r.wins,[0,0]);assert.equal(p.kills,0);assert.equal((await fetch(base+'/')).status,200);assert.equal((await fetch(base+'/server.js')).status,404);
const h=await api('create',{name:'Host'});for(let i=0;i<7;i++)assert.equal((await api('join',{name:'P'+i,code:h.state.code})).status,200);assert.equal((await api('join',{code:h.state.code})).status,400);assert.equal((await api('start',{id:h.id})).status,200);
}finally{await new Promise(r=>server.close(r))}});
test('locked room privacy and weapon purchasing, range and fire rate',async()=>{
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;async function api(a,b={}){const response=await fetch(base+'/api/'+a,{method:'POST',body:JSON.stringify(b)});return {status:response.status,...await response.json()}}
try{const a=await api('create',{name:'Host',roomName:'Private war',password:'secret'});assert.equal(a.state.locked,true);assert.equal(a.state.passwordHash,undefined);const list=await api('rooms');const found=list.rooms.find(r=>r.code===a.state.code);assert.equal(found.locked,true);assert.equal(found.passwordHash,undefined);assert.equal((await api('join',{code:a.state.code,password:'wrong'})).status,400);const b=await api('join',{code:a.state.code,password:'secret'});assert.equal(b.status,200);assert.equal((await api('loadout',{id:a.id,weapon:'smg'})).status,200);const r=rooms.get(a.state.code),[p,q]=r.players;assert.equal(p.credits,400);assert.equal(p.weapon,'smg');await api('loadout',{id:a.id,weapon:'smg'});assert.equal(p.credits,400);assert.equal((await api('loadout',{id:a.id,weapon:'invalid'})).status,400);await api('start',{id:a.id});p.x=2;p.y=10;p.angle=0;q.x=4;q.y=10;q.safeUntil=0;p.nextShot=0;shoot(r,p);assert.equal(q.hp,100);assert.equal(q.shield,30);const count=p.shots;shoot(r,p);assert.equal(p.shots,count);assert.ok(p.nextShot-Date.now()<=100);assert.equal(p.lastDamage,20);assert.equal(p.hitSerial,1);p.x=14;p.y=10;assert.equal((await api('loadout',{id:a.id,weapon:'marksman'})).status,400);p.x=2;p.y=10;assert.equal((await api('loadout',{id:a.id,weapon:'marksman'})).status,200);assert.equal(p.weapon,'marksman');assert.equal((await fetch(base+'/interface.js')).status,200);assert.equal((await fetch(base+'/movement.js')).status,200);p.ammo=3;assert.equal((await api('equip',{id:a.id,weapon:'smg'})).status,200);assert.equal((await api('equip',{id:a.id,weapon:'marksman'})).status,200);assert.equal(p.ammo,3,'switching restores the partially used magazine');
}finally{await new Promise(r=>server.close(r))}});
test('profile progression, challenge rewards, persistent guilds and regional ranked wars',async()=>{
const progression=require('./progression');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;async function api(action,data={}){const response=await fetch(base+'/api/'+action,{method:'POST',body:JSON.stringify(data)});return {status:response.status,...await response.json()}}
try{
const a=await api('profile-create',{name:'Founder',region:'South Asia',color:'#51cfe1',emblem:'Scout'}),b=await api('profile-create',{name:'Rival',region:'South Asia'}),outsider=await api('profile-create',{name:'Foreign',region:'Europe'});
assert.equal(a.profile.coins,100);assert.equal(a.profile.token,undefined);assert.equal((await api('profile-get',{profileToken:'invalid'})).status,400);assert.equal((await api('guild-create',{profileToken:a.token,name:'Early guild'})).status,400);
const p=progression.profile(a.token);await api('training-start',{profileToken:a.token,type:'aim'});let s=progression.drills.get(p.id);for(let i=0;i<10;i++){s.last=Date.now()-120;s.nextShot=0;const t=s.targets[0];t.hp=25;t.x=4;t.y=10;s.x=2;s.y=10;await api('training-input',{profileToken:a.token,fire:true,angle:0})}assert.equal(s.done,true);assert.equal(p.coins,220);await api('training-input',{profileToken:a.token});assert.equal(p.coins,220);
await api('training-start',{profileToken:a.token,type:'assault'});s=progression.drills.get(p.id);s.targets.forEach(q=>{q.hp=0;q.deadUntil=Infinity});for(let i=0;i<3;i++){s.x=25;s.y=10;s.last=Date.now()-120;await api('training-input',{profileToken:a.token});assert.equal(s.flag.carried,true);s.x=2;s.y=10;s.last=Date.now()-120;await api('training-input',{profileToken:a.token})}assert.equal(s.done,true);assert.equal(p.completed.length,2);assert.equal(p.coins,340);
const g=await api('guild-create',{profileToken:a.token,name:'Test Founders',tag:'TF'});assert.equal(g.profile.coins,90);assert.equal(g.profile.guild.members.length,1);const gid=g.profile.guild.id;
const joined=await api('guild-join',{profileToken:b.token,guildId:gid});assert.equal(joined.profile.guild.members.length,2);assert.equal((await api('guild-join',{profileToken:outsider.token,guildId:gid})).status,400);await api('guild-leave',{profileToken:b.token});const rival=progression.profile(b.token);rival.completed=['aim','capture','survive'];rival.coins=460;const rivalGuild=await api('guild-create',{profileToken:b.token,name:'Test Rivals'});assert.equal(rivalGuild.status,200);
const room=await api('create',{profileToken:a.token,ranked:true,roomName:'South Asia Rookie'});assert.equal(room.state.ranked,true);assert.equal(room.state.guilds[0],'Test Founders');assert.equal((await api('profile-edit',{profileToken:a.token,name:'Changed'})).status,400);assert.equal((await api('join',{profileToken:outsider.token,code:room.state.code})).status,400);const rivalPlayer=await api('join',{profileToken:b.token,code:room.state.code});assert.equal(rivalPlayer.status,200);await api('start',{id:room.id});const r=rooms.get(room.state.code);assert.equal(r.captureSeconds,undefined);assert.equal((await api('state',{id:room.id})).state.captureSeconds,25);assert.equal(progression.db.guilds[gid].energy,80);roundEnd(r,0);r.nextAt=0;tick();roundEnd(r,0);assert.equal(p.wins,1);assert.equal(p.coins,130);assert.equal(progression.db.guilds[gid].rating,1025);assert.equal(progression.db.guilds[gid].coins,30);
const disk=JSON.parse(require('node:fs').readFileSync(process.env.BB_DATA_FILE,'utf8'));assert.equal(disk.profiles[p.id].guildId,gid);assert.equal(disk.profiles[p.id].coins,130);assert.equal((await fetch(base+'/map-backdrop.jpg')).headers.get('content-type'),'image/jpeg');assert.equal((await fetch(base+'/GameDisplay.woff')).status,200);
}finally{await new Promise(r=>server.close(r))}});
test('FPS training enforces collisions, aim, cover, rifle damage and flag retrieval and visible enemy fire',()=>{
const prog=require('./progression');const created=prog.route('profile-create',{name:'FPS Tester'}),token=created.token;function api(a,b={}){return prog.route(a,{profileToken:token,...b})}const p=prog.profile(token);api('training-start',{type:'aim'});let s=prog.drills.get(p.id);s.last=Date.now()-120;api('training-input',{forward:1,angle:0});assert.ok(s.x>2&&s.x<2.4);s.x=5.6;s.y=5;s.last=Date.now()-120;api('training-input',{forward:1,angle:0});assert.ok(s.x<=5.7,'movement stops at wall clearance');s.targets.forEach(t=>{t.hp=0;t.deadUntil=Infinity});const q=s.targets[0];q.hp=25;q.x=8;q.y=5;s.nextShot=0;api('training-input',{fire:true,angle:0});assert.equal(q.hp,25,'wall blocks a rifle shot');s.x=2;s.y=10;s.vx=s.vy=0;q.x=4;q.y=10;s.nextShot=0;api('training-input',{fire:true,angle:Math.PI,aimX:4,aimY:10});assert.equal(q.hp,25,'world aim, not screen-click coordinates, determines hits');s.nextShot=0;api('training-input',{fire:true,angle:0,pitch:.6});assert.equal(q.hp,25,'looking above the target misses');s.nextShot=0;api('training-input',{fire:true,angle:0,pitch:0});assert.equal(q.hp,0);assert.equal(s.hits,1);
api('training-start',{type:'assault'});s=prog.drills.get(p.id);assert.equal(s.targets.length,3);s.targets.forEach(t=>{t.hp=0;t.deadUntil=Infinity});s.x=25;s.y=10;s.last=Date.now()-120;api('training-input');assert.equal(s.flag.carried,true);assert.equal(s.stage,0);s.x=2;s.y=10;s.last=Date.now()-120;api('training-input');assert.equal(s.stage,1);
api('training-start',{type:'assault'});s=prog.drills.get(p.id);s.safeUntil=0;s.targets.forEach(t=>{t.hp=0;t.deadUntil=Infinity});Object.assign(s.targets[0],{hp:100,x:4,y:10,nextShot:0});s.last=Date.now()-120;api('training-input');assert.ok(s.shield<50);assert.ok(s.tracers.length,'enemy fire produces visible shot geometry');s.hp=0;s.deadUntil=Date.now()+2000;s.last=Date.now()-120;api('training-input');assert.equal(s.failed,false,'death respawns rather than immediately failing');s.deadUntil=0;s.last=Date.now()-120;api('training-input');assert.equal(s.hp,100);assert.equal(p.coins,100);

});

test('jump physics, saved backstories, levels and regional profile positions',()=>{
const {jumpPhysics}=require('./world');const p={};jumpPhysics(p,true,.05);assert.ok(p.height>0);for(let i=0;i<40;i++)jumpPhysics(p,true,.05);assert.equal(p.height,0,'held jump does not automatically bounce');jumpPhysics(p,false,.05);jumpPhysics(p,true,.05);assert.ok(p.height>0);
const prog=require('./progression');const a=prog.route('profile-create',{name:'Lore profile',region:'Europe',backstory:'A harbor medic who stayed behind.'});const profile=prog.profile(a.token);assert.equal(a.profile.backstory,'A harbor medic who stayed behind.');assert.equal(a.profile.level,1);profile.xp=250;const b=prog.route('profile-edit',{profileToken:a.token,name:'Lore profile',backstory:'A courier rebuilding the city.'});assert.equal(b.profile.level,3);assert.equal(b.profile.xpToNext,50);assert.ok(b.profile.regionRank>=1);assert.equal(b.profile.backstory,'A courier rebuilding the city.');assert.equal(b.profile.token,undefined);
});

test('precise shot geometry, low cover and weapon hit locations',()=>{
 const {traceShot,weapons,maps}=require('./world');const r={map:0},p={x:2,y:10,angle:0,pitch:0},q={x:4,y:10,hp:100};assert.equal(traceShot(r,p,[q],weapons.rifle).damage,34);assert.equal(traceShot(r,{...p,pitch:Math.atan2(.16,2)},[q],weapons.rifle).damage,100);assert.equal(traceShot(r,p,[q],weapons.smg).damage,20);
 const edge={x:5,y:6.15,angle:0,pitch:0},enemy={x:9,y:6.15,hp:100};assert.equal(traceShot(r,edge,[enemy],weapons.rifle).target,enemy,'near a wall edge has no movement padding');assert.equal(traceShot(r,{...edge,y:5},[{...enemy,y:5}],weapons.rifle).target,null);assert.equal(traceShot(r,{x:10,y:7.5,angle:0,pitch:0},[{x:15,y:7.5,hp:100}],weapons.rifle).damage,34,'shots clear low cover');
});

test('shields absorb damage, regenerate after delay, and magazines require reload',()=>{const {combatInit,combatUpdate,damage}=require('./world');const p={hp:100};combatInit(p);damage(p,34,10000);assert.equal(p.hp,100);assert.equal(p.shield,16);damage(p,34,10001);assert.equal(p.hp,82);assert.equal(p.shield,0);combatUpdate(p,'rifle',14000,1,false);assert.equal(p.shield,0);combatUpdate(p,'rifle',16000,1,false);assert.equal(p.shield,12);p.ammo=0;combatUpdate(p,'rifle',17000,.05,true);assert.equal(p.reloadUntil,18800);combatUpdate(p,'rifle',18799,.05,false);assert.equal(p.ammo,0);combatUpdate(p,'rifle',18800,.05,false);assert.equal(p.ammo,30);assert.equal(p.reloadUntil,0)});

test('shared arcade movement is frame-rate stable, preserves slide-hop speed and blocks walls',()=>{
 const motion=require('./public/movement');const map={walls:[],wallHeights:[]};
 function run(hz){const p={x:2,y:10,angle:0};motion.reset(p);for(let i=0;i<hz;i++)motion.advance(map,p,{forward:1},1/hz);return p}
 const a=run(30),b=run(120);assert.ok(Math.abs(a.x-b.x)<1e-9);assert.ok(Math.abs(a.speed-b.speed)<1e-9);assert.ok(a.speed>4.4);
 const p=run(120);const walk=p.speed;motion.advance(map,p,{forward:1,jump:true},1/120);assert.ok(p.height>0);const airborneSpeed=p.speed;motion.advance(map,p,{},.1);assert.ok(p.speed>=airborneSpeed-.01,'momentum survives release in air');
 while(p.height>0)motion.advance(map,p,{forward:1,crouch:true},1/120);motion.advance(map,p,{forward:1,crouch:true},1/120);assert.equal(p.sliding,true);assert.ok(p.speed>walk+.5,'landing slide adds speed');const slideSpeed=p.speed;motion.advance(map,p,{forward:1,jump:true,crouch:false},1/120);assert.ok(p.height>0);assert.ok(p.speed>=slideSpeed-.05,'slide momentum carries into the next hop');
 const wallMap={walls:[[6,0,.4,20]],wallHeights:[3.6]},q={x:5,y:10,angle:0,vx:10,vy:0,height:0};motion.advance(wallMap,q,{forward:1},.12);assert.ok(q.x<=5.7);assert.equal(q.vx,0);
 motion.advance(map,a,{crouch:true},.12);assert.ok(motion.eye(a)<1.1);
});
test('low cover is landable and crouch hitboxes match the eye height',()=>{
 const motion=require('./public/movement'),{traceShot,weapons}=require('./world');const map={walls:[[4,8,2,4]],wallHeights:[.85]};
 const p={x:4.5,y:10,angle:0,height:1.05,verticalVelocity:-1};for(let i=0;i<30;i++)motion.advance(map,p,{},1/120);assert.equal(p.height,.85);assert.equal(p.grounded,true);
 const shooter={x:2,y:10,angle:0,pitch:0},target={x:4,y:10,hp:100,crouch:0};assert.equal(traceShot({map:0},shooter,[target],weapons.rifle).target,target);target.crouch=1;assert.equal(traceShot({map:0},shooter,[target],weapons.rifle).target,null,'standing eye-level shot passes above crouched player');shooter.crouch=1;assert.equal(traceShot({map:0},shooter,[target],weapons.rifle).target,target);
});

test('deathmatch rewards are repeatable per match, paid once, and tutorials do not gate guild creation',()=>{
 const prog=require('./progression'),a=prog.route('profile-create',{name:'DM Tester'}),p=prog.profile(a.token);let s=prog.route('training-start',{profileToken:a.token,type:'dm',map:1}).training;assert.equal(s.map,1);s.last=Date.now()-120;const before=s.remaining;prog.route('training-input',{profileToken:a.token,paused:true});assert.equal(s.remaining,before,'paused matches do not drain their clock');s.kills=5;s.remaining=.01;s.last=Date.now()-120;prog.route('training-input',{profileToken:a.token});assert.equal(s.done,true);assert.equal(s.reward,50);assert.equal(p.coins,150);prog.route('training-input',{profileToken:a.token});assert.equal(p.coins,150,'result polling never pays twice');p.coins=250;const founded=prog.route('guild-create',{profileToken:a.token,name:'DM Earned Guild'});assert.equal(founded.profile.guild.name,'DM Earned Guild');assert.equal(p.completed.length,0,'tutorials are optional');
 const legacy={completed:['aim','capture','survive']};assert.equal(prog.tutorialCount(legacy),2);
});
test('online team deathmatch has free entry, kill scoring, draws and one-time personal payouts',async()=>{
 const prog=require('./progression');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;async function api(action,data={}){const response=await fetch(base+'/api/'+action,{method:'POST',body:JSON.stringify(data)});return response.json()}
 try{const profile=await api('profile-create',{name:'Team DM'}),a=await api('create',{profileToken:profile.token,mode:'tdm'}),b=await api('join',{code:a.state.code,name:'Opponent'});const started=await api('start',{id:a.id});assert.deepEqual(started.state.energy,[100,100]);assert.deepEqual(started.state.zones,[]);const r=rooms.get(a.state.code),[p,q]=r.players;p.x=2;p.y=10;p.angle=0;q.x=4;q.y=10;q.safeUntil=0;q.shield=0;for(let i=0;i<3;i++){p.nextShot=0;shoot(r,p)}assert.equal(r.score[0],1);r.remaining=.01;p.input={};q.deadUntil=Infinity;tick();assert.equal(r.phase,'results');assert.equal(prog.profile(profile.token).coins,130);roundEnd(r,0);assert.equal(prog.profile(profile.token).coins,130,'match payouts are idempotent');const c=await api('create',{mode:'tdm'}),d=await api('join',{code:c.state.code});await api('start',{id:c.id});const draw=rooms.get(c.state.code);draw.remaining=0;tick();assert.equal(draw.phase,'results');assert.equal(draw.winner,-1);
 }finally{await new Promise(r=>server.close(r))}
});

test('rifle distinguishes head, torso and legs and cover stops shots',()=>{const {traceShot,weapons}=require('./world');const p={x:2,y:10,angle:0,pitch:0},q={x:4,y:10,hp:100};const leg=traceShot({map:0},{...p,pitch:Math.atan2(.45-1.55,2)},[q],weapons.rifle);assert.equal(leg.zone,'limb');assert.equal(leg.damage,22);const head=traceShot({map:0},{...p,pitch:Math.atan2(1.73-1.55,2)},[q],weapons.rifle);assert.equal(head.zone,'head');assert.equal(head.damage,100);assert.equal(traceShot({map:0},p,[q],weapons.rifle).damage,34)});

test('expanded maps connect spawns and allow movement beyond the old arena',()=>{const {maps,blocked}=require('./world');const movement=require('./public/movement');for(let map=0;map<maps.length;map++){const m=maps[map];assert.equal(m.width,64);assert.equal(m.depth,44);const seen=new Set(['3,10']),queue=[[3,10]];for(let at=0;at<queue.length;at++){const [x,y]=queue[at];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&!blocked({map},nx+.5,ny+.5)){seen.add(k);queue.push([nx,ny])}}}for(const p of [...m.spawns,...m.botSpawns])assert.ok(seen.has(Math.floor(p.x)+','+Math.floor(p.y)));const p={x:58,y:40,angle:0};movement.reset(p);movement.advance(m,p,{forward:1},.1);assert.ok(p.x>58);assert.ok(blocked({map},64,40));}});

test('point-blank cover clips shot endpoints and crates stop crouched rays',()=>{const {traceShot,weapons}=require('./world');const p={x:5.65,y:3,angle:0,pitch:0},q={x:8,y:3,hp:100};const wall=traceShot({map:0},p,[q],weapons.rifle);assert.equal(wall.target,null);assert.ok(Math.abs(wall.to[0]-6)<1e-8);assert.ok(wall.to[0]-wall.from[0]<.4);const crate=traceShot({map:0},{x:9,y:16.5,angle:0,pitch:0,height:0,crouch:1.6},[{x:13,y:16.5,hp:100}],weapons.rifle);assert.equal(crate.target,null);assert.ok(Math.abs(crate.to[0]-10.65)<1e-8)});

test('shots clear low cover when the authoritative eye is above it, including standing on cover',()=>{const {maps,traceShot,weapons}=require('./world');maps.push({width:20,depth:20,walls:[[3,2,1,2]],wallHeights:[1.2]});const map=maps.length-1;try{const p={x:2.5,y:3,angle:0,pitch:0},q={x:6,y:3,hp:100};assert.equal(traceShot({map},p,[q],weapons.rifle).target,q);assert.equal(traceShot({map},{...p,crouch:1},[q],weapons.rifle).target,null);const elevated={...p,x:3.5,height:1.2,pitch:Math.atan2(1.65-2.75,2.5)};assert.equal(traceShot({map},elevated,[q],weapons.rifle).target,q);}finally{maps.pop()}});
test('recoil climbs, changes yaw during long sprays, supports counter-aim and resets after recovery',()=>{const {recoil}=require('./world');const p={angle:0,pitch:0,vx:0,vy:0,grounded:true};recoil.reset(p);const centered=()=>.5;let shot;for(let i=0;i<12;i++)shot=recoil.fire(p,'rifle',1000+i*150,false,centered);assert.ok(p.recoilPitch>.08);assert.ok(Math.abs(p.recoilYaw)>.01);const raised=shot.pitch;p.pitch=-.07;const compensated=recoil.fire(p,'rifle',2900,false,centered);assert.ok(compensated.pitch<raised);for(let i=0;i<120;i++)recoil.update(p,'rifle',4000+i*8,1/120);assert.equal(p.sprayCount,0);assert.equal(p.recoilPitch,0);assert.equal(p.recoilYaw,0);recoil.reset(p);const first=recoil.fire(p,'rifle',6000,false,centered);assert.ok(Math.abs(first.pitch-p.pitch)<.002);});
