// Cases derived from Riot hit-registration/recoil articles and Valve collision utilities.
const {test}=require('node:test'),assert=require('node:assert/strict');
const {maps,rayBox,traceShot,weapons,recoil,addTracer,combatInit,combatUpdate}=require('./world');
const motion=require('./public/movement');
function fixture(fn){maps.push({width:100,depth:100,walls:[],wallHeights:[],propWalls:[]});try{return fn(maps.length-1,maps.at(-1))}finally{maps.pop()}}
let seed=71;function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}
function faceOracle(o,d,lo,hi,range){if(o.every((v,i)=>v>=lo[i]&&v<=hi[i]))return 0;const hits=[];for(let axis=0;axis<3;axis++)for(const face of [lo[axis],hi[axis]]){if(Math.abs(d[axis])<1e-8)continue;const t=(face-o[axis])/d[axis];if(t<0||t>range)continue;const point=o.map((v,i)=>v+t*d[i]);if(point.every((v,i)=>v>=lo[i]-1e-9&&v<=hi[i]+1e-9))hits.push(t)}return hits.length?Math.min(...hits):Infinity}
test('2,000 independent ray/box comparisons: faces, negative direction and bounded ranges',()=>{for(let n=0;n<2000;n++){const o=Array.from({length:3},()=>random()*12-6),d=Array.from({length:3},()=>random()*2-1),lo=Array.from({length:3},()=>random()*4-2),hi=lo.map(v=>v+random()*3+.01),range=random()*20;const expected=faceOracle(o,d,lo,hi,range),got=rayBox(o,d,lo,hi,range);assert.ok(got===expected||Math.abs(got-expected)<1e-8,JSON.stringify({o,d,lo,hi,range,expected,got}))}});
test('parallel, grazing, start-solid, behind-origin and range-boundary rays',()=>{const lo=[1,1,1],hi=[2,2,2];assert.equal(rayBox([0,1,1],[1,0,0],lo,hi),1);assert.equal(rayBox([0,.99,1],[1,0,0],lo,hi),Infinity);assert.equal(rayBox([1.5,1.5,1.5],[1,0,0],lo,hi),0);assert.equal(rayBox([3,1.5,1.5],[1,0,0],lo,hi),Infinity);assert.equal(rayBox([0,1.5,1.5],[1,0,0],lo,hi,.99),Infinity);assert.equal(rayBox([0,1.5,1.5],[1,0,0],lo,hi,1),1)});
test('384 cover combinations: four directions, standing/crouching, elevated eyes, distance and cover height',()=>fixture((map,m)=>{for(const axis of [0,1,2,3])for(const height of [.35,.75,.9,1.2,1.6,2.8])for(const crouch of [0,1])for(const elevation of [0,1.2])for(const distance of [5,9,15,25]){const angle=axis*Math.PI/2,dx=Math.cos(angle),dz=Math.sin(angle),p={x:30,y:30,angle,pitch:0,crouch,height:elevation},q={x:30+dx*distance,y:30+dz*distance,hp:100,height:elevation,crouch};const eye=elevation+motion.eye(p);m.walls=[[30+dx*2-(axis%2?1:.4),30+dz*2-(axis%2?.4:1),axis%2?2:.8,axis%2?.8:2]];m.wallHeights=[height];const shot=traceShot({map},p,[q],weapons.rifle);assert.equal(!!shot.target,eye>height,JSON.stringify({axis,height,crouch,elevation,distance,eye}));if(!shot.target)assert.ok(Math.hypot(...shot.to.map((v,i)=>v-shot.from[i]))<3)}}));
test('nearest living target wins regardless of target array order, walls override hits',()=>fixture((map,m)=>{const p={x:2,y:10,angle:0,pitch:0},near={x:5,y:10,hp:100},far={x:8,y:10,hp:100};assert.equal(traceShot({map},p,[far,near],weapons.rifle).target,near);assert.equal(traceShot({map},p,[{...near,hp:0},far],weapons.rifle).target,far);m.walls=[[3,9,1,2]];m.wallHeights=[3];assert.equal(traceShot({map},p,[near,far],weapons.rifle).target,null)}));
test('standing and crouched head/torso/leg hits follow vertical scale, with pitched elevated targets',()=>fixture(map=>{for(const crouch of [0,.5,1])for(const elevation of [0,.85,2])for(const [zone,y]of [['head',1.72],['body',1.2],['limb',.4]]){const scale=1-crouch*.3,p={x:10,y:2,angle:Math.PI/2,pitch:Math.atan2(elevation+y*scale-1.55,6)},q={x:10,y:8,hp:100,height:elevation,crouch};const shot=traceShot({map},p,[q],weapons.rifle);assert.equal(shot.zone,zone);assert.equal(shot.damage,zone==='head'?100:zone==='body'?34:22)}}));
test('platform landings at 30/60/144 FPS preserve authoritative eye clearance',()=>fixture((map,m)=>{m.walls=[[3,2,2,2]];m.wallHeights=[.85];for(const fps of [30,60,144]){const p={x:3.5,y:3,angle:0};motion.reset(p);p.height=2;p.verticalVelocity=-1;p.grounded=false;for(let i=0;i<fps;i++)motion.advance(m,p,{},1/fps);assert.ok(Math.abs(p.height-.85)<1e-8);assert.ok(p.grounded);const q={x:8,y:3,hp:100};p.pitch=Math.atan2(1.2-(p.height+motion.eye(p)),4.5);assert.equal(traceShot({map},p,[q],weapons.rifle).target,q)}}));
test('recorded tracers exactly match authoritative start, endpoint and hit classification',()=>fixture(map=>{const r={map},p={x:2,y:10,angle:0,pitch:0},q={x:4,y:10,hp:100};const shot=traceShot(r,p,[q],weapons.rifle);addTracer(r,shot);const t=r.tracers[0];assert.deepEqual(t.from,shot.from);assert.deepEqual(t.to,shot.to);assert.equal(t.zone,shot.zone);assert.equal(t.hit,true)}));
test('all weapons: finite bounded spray, protected early yaw, ADS/crouch control and movement/air error',()=>{for(const weapon of Object.keys(weapons)){function first(extra={},aim=false){const p={angle:0,pitch:0,grounded:true,...extra};recoil.reset(p);return {p,shot:recoil.fire(p,weapon,1000,aim,()=>.75)}}const standing=first(),aim=first({},true),crouch=first({crouch:1}),moving=first({vx:4.5}),air=first({grounded:false});assert.ok(aim.p.recoilPitch<standing.p.recoilPitch);assert.ok(crouch.p.recoilPitch<standing.p.recoilPitch);assert.ok(Math.abs(moving.shot.pitch)>Math.abs(standing.shot.pitch));assert.ok(Math.abs(air.shot.pitch)>Math.abs(moving.shot.pitch));const p={angle:0,pitch:0,grounded:true};recoil.reset(p);for(let n=0;n<200;n++){const shot=recoil.fire(p,weapon,1000+n*80,false,random);assert.ok(Number.isFinite(shot.pitch)&&Number.isFinite(shot.angle));assert.ok(p.recoilPitch<=recoil.tuning[weapon].max);assert.ok(Math.abs(p.recoilYaw)<=.045);if(n<5)assert.equal(p.recoilYaw,0)}recoil.update(p,'rifle',30000,.1);if(weapon!=='rifle')assert.equal(p.sprayCount,0)}});
test('recoil reset on respawn, magazine refill only after reload deadline',()=>{const p={hp:100,angle:0,pitch:0};combatInit(p);recoil.fire(p,'rifle',1000);combatInit(p);assert.equal(p.recoilPitch,0);assert.equal(p.sprayCount,0);p.ammo=0;combatUpdate(p,'rifle',2000,.016,false);assert.equal(p.ammo,0);combatUpdate(p,'rifle',3799,.016,false);assert.equal(p.ammo,0);combatUpdate(p,'rifle',3800,.016,false);assert.equal(p.ammo,30)});

test('facing the shooter rotates torso and limb hitboxes consistently across 36 facing directions',()=>fixture(map=>{for(const angle of Array.from({length:36},(_,i)=>i*Math.PI/18)){const p={x:30,y:30,angle,pitch:Math.atan2(1.2-1.55,6)},q={x:30+Math.cos(angle)*6,y:30+Math.sin(angle)*6,angle:angle+Math.PI,hp:100};assert.equal(traceShot({map},p,[q],weapons.rifle).zone,'body',String(angle))}}));
